const express = require("express");
const dotenv = require("dotenv");
const path = require("path");
const authRoutes = require("./routes/authRoutes");
const userRoutes = require("./routes/userRoutes");
const addressRoutes = require("./routes/addRoutes");
const otpRoutes = require("./routes/otpRoutes");
const phoneOtpRoutes = require("./routes/phoneOtp");
const imageRoutes = require("./routes/onlyImageRoutes");
const foodRoutes = require("./routes/foodRoutes");
const restaurantRoutes = require("./routes/restaurantRoutes");
const paymentRoutes = require("./routes/paymentRoutes");
const placeOrderRoutes=require("./routes/placeorderAddressRoutes");
const ordersRoutes=require("./routes/orderRoutes");
const orderhistoryRoutes=require("./routes/orderhistoryRoutes");
dotenv.config();
const app = express();
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

app.use("/auth", authRoutes);
app.use("/phone", phoneOtpRoutes);
app.use("/users", userRoutes);
app.use("/uploads", express.static("uploads"));
app.use("/address", addressRoutes);
app.use("/otp", otpRoutes);
app.use("/restaurant", restaurantRoutes);
app.use("/image_add", imageRoutes);
app.use("/food", foodRoutes);
app.use("/payment", paymentRoutes);
app.use('/plae',placeOrderRoutes);
app.use('/order',ordersRoutes);
app.use('/orderhistory',orderhistoryRoutes);
app.use("/orderhistoryAdd",orderhistoryRoutes);

const PORT = process.env.PORT || 3000;
app.listen(PORT, (err) => {
    if (err) return console.error("server error :" + err.message);
    console.log(`server running on port ${PORT}`);
});
